const Sdata = {
  shopItems: [
    {
      id: 7,
      cover: "./images/shops/shops-1.png",
      name: "Uniformes",
      price: " ",
      discount: " ",
    },
    {
      id: 8,
      cover: "./images/shops/shops-2.png",
      name: "Livros",
      price: " ",
      discount: " ",
    },
    {
      id: 9,
      cover: "./images/shops/shops-3.png",
      name: "Acessorios escolares",
      price: " ",
      discount: "  ",
    },
    {
      id: 10,
      cover: "./images/shops/shops-4.png",
      name: "Fantasias",
      price: " ",
      discount: "  ",
    },
    {
      id: 11,
      cover: "./images/shops/shops-5.png",
      name: "Brinquedos",
      price: " ",
      discount: "  ",
    },
    {
      id: 12,
      cover: "./images/shops/shops-7.png",
      name: "Eletrônicos",
      price: " ",
      discount: "  ",
    },
    {
      id: 13,
      cover: "./images/shops/shops-8.png",
      name: "Roupas em geral",
      price: " ",
      discount: " ",
    },
    {
      id: 14,
      cover: "./images/shops/shops-9.png",
      name: "Calçados",
      price: " ",
      discount: " ",
    },
    {
      id: 15,
      cover: "./images/shops/shops-10.png",
      name: "Móveis / Acessórios",
      price: " ",
      discount: " ",
    },
    {
      id: 13,
      cover: "./images/shops/shops-8.png",
      name: "Esporte",
      price: " ",
      discount: " ",
    },
    {
      id: 14,
      cover: "./images/shops/shops-9.png",
      name: "Instrumentos Musicais",
      price: " ",
      discount: " ",
    },
    {
      id: 15,
      cover: "./images/shops/shops-10.png",
      name: "Maternidade",
      price: " ",
      discount: " ",
    },
  ],
}
export default Sdata
